/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dr_evomodel_substmodel_eigen_EigenJNIWrapper */

#ifndef _Included_dr_evomodel_substmodel_eigen_EigenJNIWrapper
#define _Included_dr_evomodel_substmodel_eigen_EigenJNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dr_evomodel_substmodel_eigen_EigenJNIWrapper
 * Method:    createInstance
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dr_evomodel_substmodel_eigen_EigenJNIWrapper_createInstance
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dr_evomodel_substmodel_eigen_EigenJNIWrapper
 * Method:    setMatrix
 * Signature: (I[I[DII)I
 */
JNIEXPORT jint JNICALL Java_dr_evomodel_substmodel_eigen_EigenJNIWrapper_setMatrix
  (JNIEnv *, jobject, jint, jintArray, jdoubleArray, jint, jint);

/*
 * Class:     dr_evomodel_substmodel_eigen_EigenJNIWrapper
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_dr_evomodel_substmodel_eigen_EigenJNIWrapper_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     dr_evomodel_substmodel_eigen_EigenJNIWrapper
 * Method:    getEigenDecomposition
 * Signature: (I[D[D[D)I
 */
JNIEXPORT jint JNICALL Java_dr_evomodel_substmodel_eigen_EigenJNIWrapper_getEigenDecomposition
  (JNIEnv *, jobject, jint, jdoubleArray, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
